spring.application.name=baozi-store

jwt.secret=baozi-store-jwt-secret-key-2026-very-secure-key
jwt.expiration=86400000

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect